image: collaborating.tuhh.de:5005/e-4/utilities/docker-images/ci-latex

build:
  stage: build
  script:
    - pdflatex -interaction=nonstopmode demo_tuhh_presentation
  artifacts:
    paths:
      - demo_tuhh_presentation.pdf
