stages:
  - build
  - release

build_job:
  stage: build
  image: collaborating.tuhh.de:5005/e-4/utilities/docker-images/ci-latex
  script:
    - latexmk -pdf demo_tuhh_presentation
  environment:
    name: demo_tuhh_presentation/$CI_COMMIT_REF_NAME
    url: $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/demo_tuhh_presentation.pdf
  artifacts:
    paths:
      - demo_tuhh_presentation.pdf

release_job:
  stage: release
  image: collaborating.tuhh.de:5005/e-4/utilities/docker-images/ci-latex
  rules:
    - if: $CI_COMMIT_BRANCH == "master"  # Run this job when commits are merged into master branch
  script:
    - echo "running release_job for $TAG"
  release:                                        
    tag_name: 'v0.$CI_PIPELINE_IID'
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'